sudo: false
language: node_js

before_install:
- wget https://github.com/Shopify/toxiproxy/releases/download/v2.0.0rc2/toxiproxy_2.0.0rc2_amd64.deb
- dpkg -i ./toxiproxy_2.0.0rc2_amd64.deb
- service toxiproxy start
before_script:
- typings install