sudo: required
language: node_js

before_install:
- wget -O toxiproxy_2.0.0rc2_amd64.deb https://github.com/Shopify/toxiproxy/releases/download/v2.0.0rc2/toxiproxy_2.0.0rc2_amd64.deb
- sudo dpkg -i ./toxiproxy_2.0.0rc2_amd64.deb
- sudo service toxiproxy start
before_script:
- typings install
- npm run lint